[tool.ruff]
line-length = 100
target-version = "py313"
exclude = [".venv", "node_modules", "build", "dist"]
lint.select = ["E", "F", "I", "B", "UP", "S"]
lint.ignore = ["E501"]

[tool.mypy]
python_version = "3.13"
ignore_missing_imports = true
pretty = true
show_error_codes = true

